/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        graphite: 'var(--color-graphite)',
        steel: 'var(--color-steel)',
        raised: 'var(--color-raised)',
        'service-blue': 'var(--color-service-blue)',
        'signal-amber': 'var(--color-signal-amber)',
        'alert-red': 'var(--color-alert-red)',
        'verified-green': 'var(--color-verified-green)',
        'seal-gold': 'var(--color-seal-gold)',

        'nj-navy': 'var(--nj-navy)',
        'nj-navy-light': 'var(--nj-navy-light)',
        'nj-blue': 'var(--nj-blue)',
        'nj-blue-light': 'var(--nj-blue-light)',
        'nj-gold': 'var(--nj-gold)',
        'nj-success': 'var(--nj-success)',
        'nj-warning': 'var(--nj-warning)',
        'nj-critical': 'var(--nj-critical)',
        'nj-info': 'var(--nj-info)',

        'accent-blue': 'var(--accent-blue)',
        'accent-cyan': 'var(--accent-cyan)',
        'accent-green': 'var(--accent-green)',
        'accent-red': 'var(--accent-red)',
        'accent-amber': 'var(--accent-amber)',

        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'bg-raised': 'var(--bg-raised)',
        'bg-card': 'var(--bg-card)',
        'bg-sidebar': 'var(--bg-sidebar)',
        'bg-header': 'var(--bg-header)',
        'bg-dark': 'var(--bg-dark)',

        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-inverse': 'var(--text-inverse)',

        'border-primary': 'var(--border-primary)',
        'border-secondary': 'var(--border-secondary)',

        'hover-bg': 'var(--hover-bg)',
        'selection-bg': 'var(--selection-bg)',

        'glass-bg': 'var(--glass-bg)',
        'glass-border': 'var(--glass-border)',

        // ── KSP login flow design system (spec source of truth) ──
        'ksp-navy': '#0A1628',
        'ksp-navy-mid': '#0F2040',
        'ksp-navy-light': '#1A3358',
        'ksp-steel': '#2B4C7E',
        'ksp-amber': '#F59E0B',
        'ksp-white': '#F8FAFC',
        'ksp-muted': '#94A3B8',
        'ksp-danger': '#EF4444',
        'ksp-success': '#10B981',
        'ksp-glass': '#0F2040',
      },
      fontFamily: {
        display: ['Archivo', 'Noto Sans Kannada', 'system-ui', 'sans-serif'],
        sans: ['IBM Plex Sans', 'Noto Sans Kannada', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        kannada: ['Noto Sans Kannada', 'Noto Serif Kannada', 'serif'],
      },
      letterSpacing: {
        console: '0.12em',
      },
      fontSize: {
        display: ['2rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'heading-xl': ['1.75rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'heading-l': ['1.5rem', { lineHeight: '1.25', fontWeight: '700', letterSpacing: '-0.015em' }],
        'heading-m': ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-s': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
        body: ['0.875rem', { lineHeight: '1.6' }],
        caption: ['0.75rem', { lineHeight: '1.5' }],
        micro: ['0.625rem', { lineHeight: '1.4' }],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        6: '24px',
        8: '32px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '16px',
        xl: '16px',
        full: '9999px',
      },
      boxShadow: {
        floating: 'var(--shadow-floating)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '400ms',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-in-up': { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-down': { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-scale': { '0%': { opacity: '0', transform: 'scale(0.96)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'panel-enter': { '0%': { opacity: '0', transform: 'translateY(4px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        skeleton: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        'score-fill': { '0%': { strokeDashoffset: 'var(--score-offset-start)' }, '100%': { strokeDashoffset: 'var(--score-offset-end)' } },
        'slide-up': { '0%': { transform: 'translateY(10px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'pulse-glow': { '0%, 100%': { boxShadow: '0 0 8px var(--accent-cyan)', opacity: '0.6' }, '50%': { boxShadow: '0 0 20px var(--accent-cyan)', opacity: '1' } },
        'ping-large': { '0%': { transform: 'scale(1)', opacity: '0.8' }, '100%': { transform: 'scale(2.5)', opacity: '0' } },
        'scan-line': { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100vh)' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        'glow-pulse': { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '0.8' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'border-glow': { '0%, 100%': { borderColor: 'rgba(62, 110, 150, 0.2)' }, '50%': { borderColor: 'rgba(62, 110, 150, 0.5)' } },
        'slide-in-right': { '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-out-right': { '0%': { transform: 'translateX(0)', opacity: '1' }, '100%': { transform: 'translateX(100%)', opacity: '0' } },
        'scale-in': { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'spin-slow': { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        'badge-pop': { '0%': { transform: 'scale(0.5)', opacity: '0' }, '50%': { transform: 'scale(1.2)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'fade-in-up': 'fade-in-up 200ms ease-out',
        'fade-in-down': 'fade-in-down 120ms ease-out',
        'fade-in-scale': 'fade-in-scale 250ms ease-out',
        'panel-enter': 'panel-enter 120ms ease-out',
        skeleton: 'skeleton 1.5s ease-in-out infinite',
        'score-fill': 'score-fill 1s ease-out forwards',
        'slide-up': 'slide-up 0.2s ease-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'ping-large': 'ping-large 1.5s ease-out infinite',
        'scan-line': 'scan-line 8s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        'border-glow': 'border-glow 2s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 200ms ease-out',
        'slide-out-right': 'slide-out-right 200ms ease-out',
        'scale-in': 'scale-in 150ms ease-out',
        'spin-slow': 'spin-slow 3s linear infinite',
        'badge-pop': 'badge-pop 300ms cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
};
