"""FIR Report PDF generator using fpdf2.

Usage::

    from backend.pdf.engine import FIRReportPDF
    pdf = FIRReportPDF()
    pdf.add_fir_report(fir_data)
    pdf.output("report.pdf")
"""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any

from fpdf import FPDF

logger = logging.getLogger("nj.pdf.engine")

# Colour palette
KSP_NAVY = (12, 25, 41)
KSP_GOLD = (245, 158, 11)
KSP_WHITE = (232, 237, 245)
KSP_MUTED = (107, 125, 158)
KSP_RED = (239, 68, 68)
KSP_GREEN = (34, 197, 94)


class FIRReportPDF(FPDF):
    """A4 PDF generator for FIR case reports."""

    def __init__(self) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=20)

    # ── Header (appears on every page) ─────────────────────────────────────

    def header(self) -> None:
        if self.page_no() == 1:
            return  # custom header on page 1
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*KSP_MUTED)
        self.cell(0, 8, "Neural Justice - Karnataka State Police", align="L")
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 15, 200, 15)
        self.ln(4)

    # ── Footer ─────────────────────────────────────────────────────────────

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 6)
        self.set_text_color(*KSP_MUTED)
        self.cell(0, 10, "Confidential - For official use only | Generated by Neural Justice", align="C")

    # ── Top-level report builder ───────────────────────────────────────────

    def add_fir_report(self, fir: dict[str, Any]) -> None:
        """Generate a complete FIR report from a dictionary."""
        self.alias_nb_pages()
        self.set_title(f"FIR Report - {fir.get('crime_no', 'N/A')}")

        # Page 1: title block + case info
        self._add_title_page(fir)
        self._add_case_details(fir)

        # Page 2+: evidence, witnesses, diary, timeline
        self._add_evidence_table(fir.get("evidence_items", []))
        self._add_witness_table(fir.get("witnesses", []))
        self._add_case_diary(fir.get("case_diary", []))
        self._add_investigation_timeline(fir.get("investigation_timeline", []))

    # ── Internal methods ───────────────────────────────────────────────────

    def _add_title_page(self, fir: dict[str, Any]) -> None:
        """Page 1 header block with case title."""
        self.add_page()
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 12, "FIRST INFORMATION REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*KSP_MUTED)
        self.cell(0, 6, "Under Section 154 CrPC / 173 BNSS", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f"Crime No: {fir.get('crime_no', 'N/A')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

        # Horizontal rule
        self.set_draw_color(*KSP_GOLD)
        self.set_line_width(0.5)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(6)

    def _add_case_details(self, fir: dict[str, Any]) -> None:
        """Case summary table."""
        fields = [
            ("Crime Number", fir.get("crime_no", "N/A")),
            ("Date of Occurrence", fir.get("occurrence_date", "N/A")),
            ("Time", fir.get("occurrence_time", "N/A")),
            ("Crime Type", fir.get("crime_type", "N/A")),
            ("Police Station", fir.get("station_name", "N/A")),
            ("District", fir.get("district_name", "N/A")),
            ("Status", fir.get("status", "N/A")),
            ("Investigating Officer", fir.get("officer_name", "N/A")),
            ("Filing Date", fir.get("filing_date", "N/A")),
        ]

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "CASE DETAILS", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for label, value in fields:
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*KSP_MUTED)
            self.cell(50, 5, label, border=0)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*KSP_NAVY)
            self.cell(0, 5, str(value), new_x="LMARGIN", new_y="NEXT")

        self.ln(4)

        # Brief facts
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "BRIEF FACTS", new_x="LMARGIN", new_y="NEXT")
        self.ln(1)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*KSP_NAVY)
        self.multi_cell(0, 4.5, fir.get("brief_facts", "No description provided."))
        self.ln(4)

    def _add_evidence_table(self, evidence: list[dict[str, Any]]) -> None:
        if not evidence:
            return

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "EVIDENCE LOG", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        # Table header
        col_widths = [20, 30, 80, 30, 20]
        headers = ["ID", "Type", "Description", "Seized From", "Status"]
        self.set_font("Helvetica", "B", 7)
        self.set_fill_color(*KSP_NAVY)
        self.set_text_color(*KSP_WHITE)

        for i, h in enumerate(headers):
            self.cell(col_widths[i], 6, h, border=1, fill=True, align="C")
        self.ln()

        # Table rows
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*KSP_NAVY)
        for item in evidence:
            self.cell(col_widths[0], 5, str(item.get("id", "")), border=1, align="C")
            self.cell(col_widths[1], 5, str(item.get("type", "")), border=1, align="C")
            self.cell(col_widths[2], 5, str(item.get("description", ""))[:40], border=1)
            self.cell(col_widths[3], 5, str(item.get("seized_from", ""))[:20], border=1, align="C")
            self.cell(col_widths[4], 5, str(item.get("status", "")), border=1, align="C")
            self.ln()

        self.ln(4)

    def _add_witness_table(self, witnesses: list[dict[str, Any]]) -> None:
        if not witnesses:
            return

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "WITNESSES", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        col_widths = [20, 40, 10, 30, 60, 20]
        headers = ["ID", "Name", "Age", "Gender", "Relation", "Status"]
        self.set_font("Helvetica", "B", 7)
        self.set_fill_color(*KSP_NAVY)
        self.set_text_color(*KSP_WHITE)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 6, h, border=1, fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 7)
        self.set_text_color(*KSP_NAVY)
        for w in witnesses:
            self.cell(col_widths[0], 5, str(w.get("id", "")), border=1, align="C")
            self.cell(col_widths[1], 5, str(w.get("name", ""))[:20], border=1)
            self.cell(col_widths[2], 5, str(w.get("age", "")), border=1, align="C")
            self.cell(col_widths[3], 5, str(w.get("gender", "")), border=1, align="C")
            self.cell(col_widths[4], 5, str(w.get("relation", ""))[:30], border=1)
            self.cell(col_widths[5], 5, str(w.get("status", "")), border=1, align="C")
            self.ln()

        self.ln(4)

    def _add_case_diary(self, diary: list[dict[str, Any]]) -> None:
        if not diary:
            return

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "CASE DIARY", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for entry in diary:
            self.set_font("Helvetica", "B", 7)
            self.set_text_color(*KSP_MUTED)
            date_str = str(entry.get("date", "N/A"))
            officer_str = str(entry.get("officer", "N/A"))
            self.cell(0, 4, f"{date_str} — {officer_str}", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*KSP_NAVY)
            self.multi_cell(0, 4, str(entry.get("entry", "")))
            self.ln(2)

        self.ln(2)

    def _add_investigation_timeline(self, timeline: list[dict[str, Any]]) -> None:
        if not timeline:
            return

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*KSP_NAVY)
        self.cell(0, 6, "INVESTIGATION TIMELINE", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for event in timeline:
            event_name = str(event.get("event", "Unknown"))
            event_date = str(event.get("date", event.get("timestamp", "N/A")))
            officer = str(event.get("officer", "N/A"))

            self.set_font("Helvetica", "B", 7)
            self.set_text_color(*KSP_GOLD)
            self.cell(0, 4, f"► {event_name}", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*KSP_MUTED)
            self.cell(0, 3.5, f"{event_date} — {officer}", new_x="LMARGIN", new_y="NEXT")
            self.ln(1.5)

        self.ln(2)


def generate_fir_pdf(fir_data: dict[str, Any]) -> bytes:
    """Generate a FIR PDF and return the bytes.

    This is the main entry point for the API layer.
    """
    pdf = FIRReportPDF()
    pdf.add_fir_report(fir_data)

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.getvalue()
